language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - npm run test-coverage
after_success:
  - ./deploy.sh
# safelist
deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: feat/bullshit
