language: node_js
node_js:
  - "stable"
    
services:
  - docker
    
cache:
  directories:
    - node_modules
    - build
      
branches:
  only:
    - master

script:
  - npm run test-coverage
  - npm run build

deploy:
  skip_cleanup: true
  provider: script
  script: bash deployment/deploy.sh
  on:
    branch: master
