language: node_js
node_js:
  - "stable"
    
services:
  - docker
  - 
cache:
  directories:
    - node_modules
    - build
script:
  - npm run build
  - docker build . -t jeansaigne/website:latest
  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USERNAME" --password-stdin
  - docker push jeansaigne/website:latest
#  - npm run test-coverage

deploy:
  provider: script
  script: bash deployment/deploy.sh
  on:
    branch: feat/bullshit
    
#docker login
#docker pull
#docker-compose kill website
#docker-compose rm websi
#docker-compose up -d websie
